@url=http://localhost:3001/api
@json=Content-Type: application/json

### 测试
get http://localhost:3001

### 创建房间
post {{url}}/create
{{json}}

{
    "title": "114514"
}

### 加入房间
post {{url}}/join
{{json}}

{
    "invitation": "64a3907aa3382c36778d8cb2-ES5G2"
}